// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api.proto

package generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BottomClient is the client API for Bottom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BottomClient interface {
	RunFunction(ctx context.Context, in *Function, opts ...grpc.CallOption) (*FunctionResult, error)
}

type bottomClient struct {
	cc grpc.ClientConnInterface
}

func NewBottomClient(cc grpc.ClientConnInterface) BottomClient {
	return &bottomClient{cc}
}

func (c *bottomClient) RunFunction(ctx context.Context, in *Function, opts ...grpc.CallOption) (*FunctionResult, error) {
	out := new(FunctionResult)
	err := c.cc.Invoke(ctx, "/bottom.Bottom/RunFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BottomServer is the server API for Bottom service.
// All implementations must embed UnimplementedBottomServer
// for forward compatibility
type BottomServer interface {
	RunFunction(context.Context, *Function) (*FunctionResult, error)
	mustEmbedUnimplementedBottomServer()
}

// UnimplementedBottomServer must be embedded to have forward compatible implementations.
type UnimplementedBottomServer struct {
}

func (UnimplementedBottomServer) RunFunction(context.Context, *Function) (*FunctionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunFunction not implemented")
}
func (UnimplementedBottomServer) mustEmbedUnimplementedBottomServer() {}

// UnsafeBottomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BottomServer will
// result in compilation errors.
type UnsafeBottomServer interface {
	mustEmbedUnimplementedBottomServer()
}

func RegisterBottomServer(s grpc.ServiceRegistrar, srv BottomServer) {
	s.RegisterService(&Bottom_ServiceDesc, srv)
}

func _Bottom_RunFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Function)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BottomServer).RunFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bottom.Bottom/RunFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BottomServer).RunFunction(ctx, req.(*Function))
	}
	return interceptor(ctx, in, info, handler)
}

// Bottom_ServiceDesc is the grpc.ServiceDesc for Bottom service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bottom_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bottom.Bottom",
	HandlerType: (*BottomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunFunction",
			Handler:    _Bottom_RunFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
